name: Auto Pluto Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node index.js

      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .

      - name: echo save to file pt1
        run: |
          echo "#EXTM3U\r\n#EXT-X-INDEPENDENT-SEGMENTS\r\n" > t2.m3u8

       - name: Find line and save to file pt2
        run: |
          grep "681109b688b9d85d0938c6ba" output/plutotv_us.m3u8 >> t2.m3u8
          
          
      - name: Show result
        run: cat t2.m3u8
      - name: Commit and push T2 file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add -f t2.m3u8

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add extracted line file"

          git commit -m "Auto update playlist" || echo "No changes"
          git push --force
            git push
          fi
          git push --force
