name: Auto Pluto Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node index.js

      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update playlist" || echo "No changes"
          git push --force
      - name: Find line and save to file
        run: |
          grep -m 2 "681109b688b9d85d0938c6ba" output/plutotv_us.m3u8 > output/t2.m3u8
      - name: Show result
        run: cat output/t2.m3u8
          
